[package]
name = "chapter11_transparent_plane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-rtc = { path = "../../lib/rust-rtc" }
rand = "0.8.1"
rand_xoshiro = "0.6.0"
